### ISSUE TITLE
Create and use options pane

### ISSUE THREAD

**Issue by TimOfDestiny** [mynameiswillporter/taciturn-chrome#8]
I'd like to have options to configure the following:
- Check for session cookies, CSRF cookies, etc
- Suppress messages of <type> from domain
- Automatically set HTTP-Only on session cookies
- Detect and attempt to correct server re-issuing session cookie without HTTP only
- Detect frameworks

etc

**Comment by mynameiswillporter** [comment]
The options page is now capable of allowing the user to suppress messages from a domain.

**Comment by mynameiswillporter** [comment]
It is likely advantageous to tackle #18 before completing this as that might make this a lot easier.

**Comment by mynameiswillporter** [comment]
Closing this for now, the structure of the options will likely only become obvious once we develop more rules.
